### ISSUE TITLE
Extension loads blank page

### ISSUE THREAD

**Issue by iamphotophil** [brandonmartinez/MMSmugMugPricelistExporterExtension#1]
Hi, Thanks for this 'potentially for me' great app. But, I have an issue. Mine doesn't work, all I get is a blank page with tabs at the top?

Any advice?

Many thanks,
Phil

**Comment by brandonmartinez** [comment]
Could you send a screenshot? contact@martinezmedia.net

**Comment by iamphotophil** [comment]
Hi Brandon, 

Thanks for your prompt reply. I've reinstalled the extension and all is well!  So thank you for this excellent tool!

Best wishes,
Phil
